name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build Release x64
        run: msbuild no_activate_windows.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: no_activate_windows-x64
          path: bin/release/*.dll
